# Generated by Django 5.2 on 2025-04-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_height', models.FloatField()),
                ('board_width', models.FloatField()),
                ('game_mode', models.CharField(max_length=6)),
                ('hPadHeight', models.FloatField()),
                ('movement', models.FloatField()),
                ('last_update', models.IntegerField()),
            ],
        ),
    ]
